services:
  culcon_db:
    container_name: culcon_user_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: culcon
      POSTGRES_PASSWORD: culcon
      POSTGRES_DB: culcon_user

  app:
    image: docker.io/giangltce/culcon_user_backend:main
    container_name: culcon_user_backend
    ports:
      - "8080:8080"
    depends_on:
      - culcon_db
    environment:
      DB_URL: jdbc:postgresql://culcon_db:5432/culcon_user
      DB_USERNAME: culcon
      DB_PASSWORD: culcon
