services:
  culcon_db:
    container_name: culcon_db
    image: docker.io/pgvector/pgvector:0.8.0-pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: culcon
      POSTGRES_PASSWORD: culcon
      POSTGRES_DB: culcon

  app:
    image: docker.io/giangltce/culcon_user_backend:main
    container_name: culcon_user_backend
    ports:
      - "8080:8080"
    depends_on:
      - culcon_db
    environment:
      - DB_URL_USER=jdbc:postgresql://culcon_db:5432/culcon_user
      - DB_URL_RECORD=jdbc:postgresql://culcon_record_db:5433/culcon_record
      - DB_USERNAME=culcon
      - DB_PASSWORD=culcon
      - EMAIL_ADDRESS=culinaryconnect.777@gmail.com
      - EMAIL_PASSWORD=ukzv ubhu doze buay
