FROM docker.io/alpine/java:21-jre

WORKDIR /workdir

COPY . .

#RUN ./gradlew build --no-daemon  --parallel
COPY build/libs/backend-0.0.1-SNAPSHOT.jar /workdir/app.jar

ARG DB_USERNAME=culcon
ARG DB_PASSWORD=culcon
ARG DB_URL_USER=jdbc:h2:file:./db/culcon_user;IFEXISTS=FALSE;
ARG EMAIL_ADDRESS=culinaryconnect.777@gmail.com
ARG EMAIL_PASSWORD=ukzv ubhu doze buay
ARG CLOUDINARY_NAME=dolsfyjf7
ARG CLOUDINARY_API_KEY=788372927472331
ARG CLOUDINARY_API_SECRET=DncaBqjZ7LQtKMl12uZLLHVF4k4
ARG MONGODB_URL=mongodb+srv://culcon_guest:culcon_guest@cluster0.7djog.mongodb.net
ARG MONGODB_NAME=Culcon

ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_URL_USER=${DB_URL_USER}
ENV EMAIL_ADDRESS=${EMAIL_ADDRESS}
ENV CLOUDINARY_NAME=${CLOUDINARY_NAME}
ENV CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
ENV CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
ENV MONGODB_URL=${MONGODB_URL}
ENV MONGODB_NAME=${MONGODB_NAME}

EXPOSE 8080

ENTRYPOINT ["java","-jar","/workdir/app.jar"]
#ENTRYPOINT [ "./gradlew" , "bootRun"]
