# Build stage
FROM docker.io/openjdk:21-jdk-slim AS build
WORKDIR /app
COPY . .
RUN ./gradlew clean build -x test --parallel

# Runtime stage
FROM docker.io/alpine/java:21-jre
WORKDIR /workdir
COPY --from=build /app/build/libs/backend-0.0.1-SNAPSHOT.jar /workdir/app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/workdir/app.jar"]
