spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    user:
      url: ${DB_URL_USER}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      initialization-mode: always
    record:
      initialization-mode: always
      url: ${DB_URL_RECORD}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  data:
    mongodb:
      uri: ${MONGODB_URL}
      database: ${MONGODB_NAME}
    jpa:
      repositories:
        bootstrap-mode: default

  servlet:
    multipart:
      max-file-size: 10MB
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  mail:
    host: smtp.gmail.com
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        connectiontimeout: 5000
        timeout: 3000

jwt:
  secret-key: 482087CE4EEB98990B21E80477B6F8F7973770A5C836FF23BAA85ADCD786139B50C11D935B6C1512F36E8DA99A70788992E0EBD70F2BD5E7817CFA0D141C9270
  expiration:
    access-token: 1800000

cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
