spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
    servlet:
        multipart:
            max-file-size: 10MB
    sql:
        init:
            mode: always

    mail:
        host: smtp.gmail.com
        username: huynhhuyhuy12@gmail.com
        password: ecfw rrhf xzrw xuer
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                connectiontimeout: 5000
                timeout: 3000
                writetimeout: 5000
                debug: true



jwt:
    secret-key: 482087CE4EEB98990B21E80477B6F8F7973770A5C836FF23BAA85ADCD786139B50C11D935B6C1512F36E8DA99A70788992E0EBD70F2BD5E7817CFA0D141C9270
    expiration:
        access-token: 1800000