name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "stable", "non_stable" ]
  pull_request:
    branches: [ "main", "stable" ]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew clean assemble --parallel
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build/
            .gradle/
          retention-days: 1

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests with existing classes
        run: ./gradlew test -x compileJava -x compileTestJava

  deploy-branch:
    name: Push to Deploy Branch
    needs: test
    runs-on: ubuntu-latest
    # Only run on push to main/stable/non_stable branches, not on PRs
    if: github.event_name == 'push'
    permissions:
      contents: write
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for branch operations
      
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      
      - name: Push to deploy branch
        run: |
          # Determine target deploy branch based on source branch
          DEPLOY_BRANCH="deploy"
          
          # Create or update the deploy branch
          git checkout $DEPLOY_BRANCH
          git merge main
          git push origin $DEPLOY_BRANCH

  docker:
    name: Build and Push Docker Image
    needs: [build, test]
    runs-on: ubuntu-latest
    # Only run this job for pushes, not pull requests
    if: github.event_name == 'push'
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .

      - name: Display structure of downloaded files
        run: ls -R build/libs

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USRNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: giangltce/culcon_user_backend

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
